#!/bin/bash
	
	docker kill $(docker ps -q)
	docker rm $(docker ps -a -q)
	docker build -t res/apache_php apache-php-image/.

	docker build -t res/express_dynamic express-image/.

	docker build -t res/apache_rp apache-reverse-proxy/.

	docker run -d --name apache_static res/apache_php

	docker run -d --name express_dynamic res/express
	
	docker run -d --name apache_rp -p 8080:80 res/apache_rp