#!/bin/bash
 
 docker kill $(docker ps -q)
 docker rm $(docker ps -a -q)
 
 docker build -t res/apache_php apache-php-image/.
 docker build -t res/express express-image/.
 docker build -t res/apache_rp apache-reverse-proxy/.

docker run -d --name apache_static1 res/apache_php
docker run -d --name apache_static2 res/apache_php

docker run -d --name express_dynamic1 res/express
docker run -d --name express_dynamic2 res/express

docker inspect apache_static1 | grep -i ipaddress
docker inspect apache_static2 | grep -i ipaddress

docker inspect express_dynamic1 | grep -i ipaddress
docker inspect express_dynamic2 | grep -i ipaddress


docker run -d -e STATIC_APP_ONE=172.17.0.2:80 -e STATIC_APP_TWO=172.17.0.3:80 -e DYNAMIC_APP_ONE=172.17.0.4:3000 -e DYNAMIC_APP_TWO=172.17.0.5:3000 --name apache-reverse-proxy -p 8080:80 res/apache_rp

docker ps -a
