#!/bin/bash
 
 docker kill $(docker ps -q)
 docker rm $(docker ps -a -q)
 
 docker build -t res/apache_php apache-php-image/.
 docker build -t res/express express-image/.
 docker build -t res/apache_rp apache-reverse-proxy/.
 
 docker run --name apache_static -d res/apache_php
 docker run --name express_dynamic -d res/express
 docker run --name apache_rp -d -p 8080:80 res/apache_rp
 
 
 docker inspect express_dynamic | grep -i ipaddress
 docker inspect apache_static | grep -i ipaddress
 docker inspect apache_rp | grep -i ipaddress
 
 
 docker ps -a